### ISSUE TITLE
Deleting a set

### ISSUE THREAD

**Issue by getapp** [Pathgather/predictor#29]
First of all, thanks for the library, it's great!
I've noticed that current API doesn't provide a way to delete a set.
For example, if we have an input matrix for articles favoured by users. If user removes an articles from favourites, then we want to reset his set. At the moment, we can either add new articles to his set or remove articles from all sets.
Is this something you have in plans to implement or would you accept a PR for this feature?

**Comment by jhdavids8** [comment]
Seems like a reasonable request, so I think a PR would be welcome!

**Comment by jhdavids8** [comment]
I believe PR #37 should satisfy your need here, so closing for now. Feel free to re-open if not though!
