### ISSUE TITLE
Question: including additional attributes in predictions

### ISSUE THREAD

**Issue by jamesprior** [Pathgather/predictor#31]
In the example for recommending a course it looks at users who have taken the course tags, and topics.  What is the recommended way to use additional information about the users who have taken a course to recommend related courses?  Eg,  a user from north america takes one course and a user in south africa takes a different course.  I'd like future users in north america to be recommended the first course.

**Comment by jhdavids8** [comment]
Hmm, you could add a matrix to courses for locations the course has been taken in (essentially locations of the users that have completed the course) and a matrix to users for location(s) they're in. That'll at least factor the location into the algorithm.

Additionally, if your location dataset is as small as one based on continent, you could have a different Redis dataset per continent using the ``redis_prefix``. This would probably be a better route if you required location to exist and did not want courses from one location to be recommended to users who were not in that location. But if that's the case, you might be better querying against the database after you fetch the courses with Predictor. That's probably as good as it gets with the way Predictor is currently built though.

If you have any ideas to better handle this, PRs are very welcome :)
