### ISSUE TITLE
Newbie: wasn't able to install it, help!

### ISSUE THREAD

**Issue by basplas** [Pathgather/predictor#32]
Hi,

I'm a Newbie in Ruby-On-Rails who just got his first full web=project setup in Ruby-On-Rails. I think that Predictor would be a perfect fit for my final project. But I'm embarrassed to say that I'm not even able to install it :(

I added redis, hiredis and predictor to the gemfile and did a `bundle install`. After that I tried to  install predictor by using `rails g predictor:install`, but that didn't give me anything.

Do I need to generate my own model or do I need to do something else? Because I don't have the predictor model or initialzer file that are mentioned in your examples.

So sorry for the typical newbie-question, but I'm stuck :)

Cheers,
Sebastian

**Comment by jhdavids8** [comment]
Hey Sebastian,

We don't have any default tasks that create the files for you, so you'll need to do that manually. As far as I know, that's not standard for Ruby gems: some implement those, but a lot don't. Our initializer file is quite simple though: the one in the Readme is all that's really needed.

Also, yep, you'll need to create your own Predictor classes that include the Predictor module, like in the Readme examples. A good place to stick those is in ``lib``

Hope that helps!

Jamie

**Comment by basplas** [comment]
Hi Jamie,

Thanks for the quick response! Prefect, then I know where to start. The only thing that isn't clear to me yet, is: can I just generate a model without fields, or do I need to add extra database-fields to the model?

Thanks for the help!

Cheers,
Sebastian

**Comment by jhdavids8** [comment]
Hey Sebastian, 

You'll of course need your data to recommend and its connections (courses, users, etc) in the database, but Predictor itself doesn't store anything in your primary database. It uses Redis as it's in-memory store where it stores identifiers and relevance scores to your primary data.

**Comment by basplas** [comment]
Okay, thanks Jamie!
