### ISSUE TITLE
users k-nearest neighbors

### ISSUE THREAD

**Issue by christoph-buente** [Pathgather/predictor#33]
I just wanted to ask, if a matrix of k-nearest neighbors is kept for every user? And if yes, how could i possibly access it. I browsed the code and it seemed to me, there is no such thing. Instead there are item-item matrices. But i just wanted to make there is or is not.

Thx, Christoph

**Comment by christoph-buente** [comment]
I thought a little bit more about the problem. I can actually inverse the input data and compute a user-user matrix by passing data like this

```recommender.add_to_matrix!(:users, "product_id", "user_23", "user_42")```

**Comment by silva96** [comment]
@christoph-buente can you elaborate more your solution?

Hi, im developing a solcial network and users can download things. I would also like to recommend a user to follow similar users based on their download activity.

For example

User 1 Downloads Thing1 and Thing2
User 2 Downloads Thing1 and Thing2
User 3 Downloads Thing9 and Thing4

Recommend User1 to follow User2

How can I achieve that?

**Comment by christoph-buente** [comment]
Hi @silva96 ,

It's a long time since I used it. But what you basically want is a User-User similarity. The tool gives you item-item similarities, if I remember correctly. That just helps with the typical Amazon statement: users who bought this item were also interested in these.

**Comment by silva96** [comment]
> Hi @silva96 ,
> 
> It's a long time since I used it. But what you basically want is a User-User similarity. The tool gives you item-item similarities, if I remember correctly. That just helps with the typical Amazon statement: users who bought this item were also interested in these.

So I can't achieve this with this gem? I thought, by reading your previous response back in 2015, you kind of solved it.
