### ISSUE TITLE
What to do with different matrix-structures?

### ISSUE THREAD

**Issue by basplas** [Pathgather/predictor#34]
Hi guys,

I love this gem, it shows surprising new relations in my data. But I do wonder what the limits are for different data-sets in Redis. I think that I actually need another matrix, or can I add labels with a different structure to the same class; or do i need to build a new classe for that? So until now (only for "projects") it works fine, but I'm still a Newbie on Redis and don't know if the following is possible:

I want to get simiarities and predictions for projects and products. I therefore want to create the following (double?) matrix:

projects:
`"user-1" -> "project-1", "project-2"`
`"product-1" -> "project-1", "project-2"`

products:
`"user-1" -> "product-1", "product-2"`
`"project-1" -> "product-1", "product-2"`
`"benefits-1" -> "product-1", "product-2"`

What to do?

**Comment by jhdavids8** [comment]
Hi,

Thanks for the kind words! 

I think I understand your setup, but if not, let me know. At the moment, you need a new class for every 'item' you want to get similarities/predictions for. So if you want to recommend users, projects, and products in your app, your setup might be:

````ruby
class ProjectPredictor
  include Predictor::Base
 
  input_matrix :users  # The users that are associated a project
  input_matrix :products  # The products that are associated to a project
end

class ProductPredictor
  include Predictor::Base
 
  input_matrix :users  # The users that are associated a product
  input_matrix :projects  # The projects that are associated to a product
end

class UserPredictor
  include Predictor::Base
 
  input_matrix :products  # The products that are associated a user
  input_matrix :projects  # The projects that are associated to a user
end
````

Depending on what you want to recommend similarities/predictions for, you'll create an instance of that recommender (e.g if you want to recommend users, create a UserPredictor).

Does that answer your question?

**Comment by basplas** [comment]
Thanks Jamie, that's exactly it. I know what to do now.

Cheers,
Sebastian

**Comment by jhdavids8** [comment]
Glad to hear it!
