### ISSUE TITLE
Excluding a product-set of my current_user when showing similar products.

### ISSUE THREAD

**Issue by basplas** [Pathgather/predictor#38]
Hi guys,

I'm trying to exclude a product-set of my current_user in a similarity set. 

products:
`"user-1" -> "product-1", "product-2"`
`"project-1" -> "product-1", "product-2"`
`"benefits-1" -> "product-1", "product-2"`

For the above matrix I want to show similarities of other users who like the same product as the current_user and also like... But the other products of the current_user shouldn't be displayed. I tried to use the following exclude, but it doesn't seem to work.

`recommender.similarities_for("product-#{@product.id}", exclusion_set: ["user-#{current_user.id}"])`

Any ideas on how to solve it?

**Comment by jhdavids8** [comment]
Howdy,

Looks like you are fetching similarities for a product but are passing in a key specific to the user. You'll need to instead pass in an array of the user's actual products, something like:
````
recommender.similarities_for("product-#{@product.id}", exclusion_set: ["product-1", "product-2"])
````
where 'product-1' and 'product-2' are owned by the current user.

Make sense?
