### ISSUE TITLE
Redis::CommandError (BUSY Redis is busy running a script. 

### ISSUE THREAD

**Issue by pt** [Pathgather/predictor#42]
I am encountering an error processing a large data set using `processing_technique :lua`.  I first used `add_matrix` for the dataset, 20k items, with up to 1k matches, using `limit_similarities_to 1000`. All the items are added, but I receive the following error ome time after calling `process!`

`Redis::CommandError (BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.)`

I am trying to figure out if I should be processing along the way, if I need to change the Redis config, or if I should revert to the Ruby processor.

**Comment by chanks** [comment]
Yeah, it makes sense that trying to add that many items at once would block for a while. You can certainly try to process items in smaller batches, or using the `:union` processing technique may help matters.

**Comment by pt** [comment]
I ended up just catching the exception, reverting to ruby for the item, then resetting the option to `:lua` and moving on. This worked well.

**Comment by chanks** [comment]
Alright, cool, thanks!
